#SI usamos BBDD embebida:
#spring:
#  datasource:
#    url: jdbc:h2:mem:newsdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

#Configuración postgres
#Desde ya pondremos variables de entorno tanto para docker como para kubernetes. En kubernetes creo los secretos y ya
#url: jdbc:postgresql://localhost:5432/martialspirit
#username: martial
#password: martial123
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

#En producción no usamos updatem usamos validate o none. Migraciones Flyway/Liquibase
# show-sql en producción no
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Para debuggear y ver lo que sucede en BBDD
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.tool.hbm2ddl: DEBUG

#Para BBDD embebida
#  h2:
#    console:
#      enabled: true
#      path: /h2-console